<a href="https://colab.research.google.com/github/pkciiti/Putorch-tutorial/blob/main/introtocolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
!pip list



Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.34.2
aiohappyeyeballs                 2.4.0
aiohttp                          3.10.5
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.16
albumentations                   1.4.15
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.19.0
astropy                          6.1.3
astropy-iers-data                0.2024.9.16.0.32.21
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            24.2.0
audioread                        3.0.1
autograd               

TENSORS


In [2]:
import torch
import numpy as np

List

In [3]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

Numpy array

In [4]:
np1=np.random.rand(3,4)
np1
np1.dtype

dtype('float64')

TENSOR

In [5]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 1.3253,  0.6714, -0.3979,  1.4150],
        [ 0.1644, -0.2698,  0.5226, -0.8458],
        [ 3.7665, -0.0589, -2.4394, -0.9453]])

In [6]:
## create numpy array to tensor
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.8216, 0.2172, 0.3404, 0.4770],
        [0.5011, 0.0272, 0.8750, 0.2142],
        [0.1515, 0.6353, 0.4031, 0.7037]], dtype=torch.float64)

Tensor operation

In [7]:
mY_tourch=torch.arange(10)
mY_tourch


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# reshape
mytorch=mY_tourch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# reshape if don know number of items using -1
mytorch2=mY_tourch.reshape(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
mytorch2=mY_tourch.reshape(-1,2)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
## view work siliar as reshape
mytorch2=mY_tourch.view(-1,2)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
## change done in origanl tensor will be refelcted in reshape and view tesor with actualy doing chnages in reshaped tensor
mytorch=mY_tourch.reshape(2,5)
mytorch
mY_tourch[1]=19
mY_tourch
mytorch

tensor([[ 0, 19,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

Sliced

In [13]:
# grab specific item
mY_tourch[1]

tensor(19)

In [14]:
# grab slice
mytorch2[:,0]

tensor([0, 2, 4, 6, 8])

In [15]:
#Retain structure i.e colum return as column
mytorch2[:,1:]

tensor([[19],
        [ 3],
        [ 5],
        [ 7],
        [ 9]])

Tensor math operation

In [16]:
tensor_1=torch.tensor([1,2,3,4])
tensor_2=torch.tensor([5,6,7,8])

In [17]:
## ADDITION
tensor_1+tensor_2


tensor([ 6,  8, 10, 12])

In [18]:
##or
torch.add(tensor_1,tensor_2)

tensor([ 6,  8, 10, 12])

In [19]:
## subtract
tensor_1-tensor_2

tensor([-4, -4, -4, -4])

In [20]:
## or sub
torch.sub(tensor_1,tensor_2)

tensor([-4, -4, -4, -4])

In [21]:
## multiplicatiomn
tensor_1*tensor_2
#or
torch.mul(tensor_1,tensor_2)

tensor([ 5, 12, 21, 32])

In [22]:
## divition
tensor_2/tensor_1

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [23]:
## or
torch.div(tensor_2,tensor_1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

Remender

In [24]:
tensor_2 % tensor_1

tensor([0, 0, 1, 0])

In [25]:
## or
torch.remainder(tensor_2,tensor_1)

tensor([0, 0, 1, 0])

In [26]:
# POWER
torch.pow(tensor_2,tensor_1)

tensor([   5,   36,  343, 4096])

# anoother way to do all operation

In [27]:
tensor_2.add(tensor_1)

tensor([ 6,  8, 10, 12])

Operation like tensor_1=tensor_1+tensor_2

In [29]:
### Basic neural network
#IRIS DATA SET 3 class 4 features
import torch
import torch.nn as nn
import torch.nn.functional as F ## allow help data move forward in fundtion i.e. function of funstion
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split



Create model class

In [39]:
class Model(nn.Module):  ## creating a class Model having nural network modulus# imput layer having 4 features of flower --> goes to hidden layer1 (n number of neuron) --> goes to hidden layer1 (n number of neuron) --> out (3 class of iris flower)
  def __init__(self,in_features=4,h1=8,h2=9,out_features=3):    ## defining and intializing the model having 4 input two hidden lyaer with 8, 9 neurons and out layer 3 neurons
     super().__init__() ## initate nn.MODule
     self.fc1=nn.Linear(in_features,h1) # define hidden layer 1 input and output
     self.fc2=nn.Linear(h1,h2)# define hidden layer 1
     self.out=nn.Linear(h2,out_features)# define output layer

  def forward(self,x): # X is output and input from eaah layer how it should move i.e. how functions are moving forwerf
    x=F.relu(self.fc1(x))
    x=F.relu(self.fc2(x))
    x=self.out(x)

    return x



In [41]:
# Create manual seed so it can give same output always
torch.manual_seed(42)
# Create instance of the model
model=Model() ## save mdoel

Load data

In [45]:
import pandas as pd ## to import data for dataframing
import matplotlib.pyplot as plt ## for matrixplot lybrary export pyploy and name it as plt
%matplotlib inline

Link

In [51]:
url="https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
my_df=pd.read_csv(url) # in url there is acsv file having features and classes
my_df.head()# see first few data .tail for last few thing
my_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

MAking classs as numaric

In [54]:
#my_df['variety'].map({'Setosa':0,'Versicolor':1,'Virginica':2})
#or
my_df['variety']=my_df['variety'].replace('Setosa',0)
my_df['variety']=my_df['variety'].replace('Versicolor',1)
my_df['variety']=my_df['variety'].replace('Virginica',2)
my_df

sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

# Train TEST split

In [57]:
X=my_df.drop('variety',axis=1).values # not having last cloum from df
y=my_df['variety'].values # last cloum

