<a href="https://colab.research.google.com/github/pkciiti/Putorch-tutorial/blob/main/introtocolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
!pip list



Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.34.2
aiohappyeyeballs                 2.4.0
aiohttp                          3.10.5
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.15
albumentations                   1.4.15
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.19.0
asn1crypto                       1.5.1
astropy                          6.1.3
astropy-iers-data                0.2024.9.16.0.32.21
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            24.2.0
audioread              

TENSORS


In [1]:
import torch
import numpy as np

List

In [2]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

Numpy array

In [6]:
np1=np.random.rand(3,4)
np1
np1.dtype

dtype('float64')

TENSOR

In [7]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-1.2842, -1.2607,  0.4218, -1.2600],
        [ 1.0180, -0.4381, -0.2257, -1.2400],
        [ 0.3641, -0.1558, -0.6808, -0.1317]])

In [8]:
## create numpy array to tensor
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.9431, 0.9132, 0.7597, 0.1346],
        [0.0423, 0.1022, 0.1065, 0.4713],
        [0.6920, 0.1680, 0.0538, 0.9920]], dtype=torch.float64)

Tensor operation

In [14]:
mY_tourch=torch.arange(10)
mY_tourch


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# reshape
mytorch=mY_tourch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
# reshape if don know number of items using -1
mytorch2=mY_tourch.reshape(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
mytorch2=mY_tourch.reshape(-1,2)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
## view work siliar as reshape
mytorch2=mY_tourch.view(-1,2)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [22]:
## change done in origanl tensor will be refelcted in reshape and view tesor with actualy doing chnages in reshaped tensor
mytorch=mY_tourch.reshape(2,5)
mytorch
mY_tourch[1]=19
mY_tourch
mytorch

tensor([[ 0, 19,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

Sliced

In [23]:
# grab specific item
mY_tourch[1]

tensor(19)

In [25]:
# grab slice
mytorch2[:,0]

tensor([0, 2, 4, 6, 8])

In [41]:
#Retain structure i.e colum return as column
mytorch2[:,1:]

tensor([[19],
        [ 3],
        [ 5],
        [ 7],
        [ 9]])

Tensor math operation

In [43]:
tensor_1=torch.tensor([1,2,3,4])
tensor_2=torch.tensor([5,6,7,8])

In [46]:
## ADDITION
tensor_1+tensor_2


tensor([ 6,  8, 10, 12])

In [47]:
##or
torch.add(tensor_1,tensor_2)

tensor([ 6,  8, 10, 12])

In [48]:
## subtract
tensor_1-tensor_2

tensor([-4, -4, -4, -4])

In [49]:
## or sub
torch.sub(tensor_1,tensor_2)

tensor([-4, -4, -4, -4])

In [50]:
## multiplicatiomn
tensor_1*tensor_2
#or
torch.mul(tensor_1,tensor_2)

tensor([ 5, 12, 21, 32])

In [51]:
## divition
tensor_2/tensor_1

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [52]:
## or
torch.div(tensor_2,tensor_1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

Remender

In [53]:
tensor_2 % tensor_1

tensor([0, 0, 1, 0])

In [54]:
## or
torch.remainder(tensor_2,tensor_1)

tensor([0, 0, 1, 0])

In [55]:
# POWER
torch.pow(tensor_2,tensor_1)

tensor([   5,   36,  343, 4096])

# anoother way to do all operation

In [56]:
tensor_2.add(tensor_1)

tensor([ 6,  8, 10, 12])

Operation like tensor_1=tensor_1+tensor_2

In [57]:
tensor_1.add_tensor_2
tensor_1

AttributeError: 'Tensor' object has no attribute 'add_tensor_2'